---------------------------------------------------
DELETE
FROM INTERNADO
WHERE PAC_ID_PACIENTE = 225565         ;

SELECT *
FROM EVOLUCION_MEDICA
WHERE INTERNADO_ID_INTERNADO = 248740 ;

DELETE
FROM EVOLUCION_MEDICA
WHERE id_evolucion = 5185243;

---------------------------------------------------
--HOJA INGRESO
DELETE
FROM   HIST_CLI_ANT_DIAG
WHERE  HCE_EMA_ID_EVOLUCION = 5030591;

DELETE
FROM   HIST_CLI_ANTECEDENTE
WHERE  EMA_ID_EVOLUCION = 5030591;

DELETE
FROM   INDICACION_HOJA_INGRESO
WHERE  EMA_ID_EVOLUCION = 5030591;

---------------------------------------------------
--HOJA UTI ADULTO INGRESO

DELETE
FROM  HOJA_UTI_ADU_DIAG
WHERE HUO_ID_HOJA = 15144;

SELECT id_hoja
FROM  HOJA_UTI_ADULTO
WHERE EMA_ID_EVOLUCION = 5030918;

DELETE
FROM  HOJA_UTI_ADULTO
WHERE EMA_ID_EVOLUCION = 5030918;

---------------------------------------------------
--EVOLUCION MÉDICA

DELETE
FROM EVO_MED_DIAG
WHERE EMA_ID_EVOLUCION = 5185241;

---------------------------------------------------
--EVOLUCION MEDICA ESTUDIO
DELETE
FROM EVOLUCION_MEDICA_ESTUDIO
WHERE EMA_ID_EVOLUCION =  5184607;


-----------------------------
--HOJA ENFERMERIA
--anamnesis.heh_ema_fk
DELETE
FROM HOJA_ENFERMERIA_HIST
WHERE EMA_ID_EVOLUCION = 5173997;

--anamnesis.HEA_ema_fk
DELETE
FROM HOJA_ENFERMERIA
WHERE EMA_ID_EVOLUCION = 5173997;

-----------------------------------

DELETE
FROM  TECNICA_QUIRURGICA
WHERE INTERNADO_ID_INTERNADO = 248740;

DELETE
FROM  OCUPACION_SALA_HIST
WHERE INTERNADO_ID_INTERNADO =248740 ;

 COMMIT;



ROLLBACK;