
PROMPT Creating Table 'GRUPO_HOJA_HC_JN'
CREATE TABLE ANAMNESIS.GRUPO_HOJA_HC_JN
 (JN_OPERATION  CHAR(3) NOT NULL
 ,JN_ORACLE_USER  VARCHAR2(30) NOT NULL
 ,JN_DATETIME  DATE NOT NULL
 ,JN_NOTES  VARCHAR2(240)
 ,JN_APPLN  VARCHAR2(35)
 ,JN_SESSION  NUMBER(38)
 ,ID_GRUPO_HOJA_HC  NUMBER(20) NOT NULL
 ,GRUPO  VARCHAR2(50)
 ,OBS  VARCHAR2(4000)
 )
/

COMMENT ON TABLE GRUPO_HOJA_HC_JN IS 'Created by Oracle Designer Server Generator'
/

PROMPT Creating Table 'GRUPO_HOJA_HC'
CREATE TABLE ANAMNESIS.GRUPO_HOJA_HC
 (ID_GRUPO_HOJA_HC  NUMBER(20) NOT NULL
 ,GRUPO  VARCHAR2(50) NOT NULL
 ,OBS  VARCHAR2(4000)
 )
/

PROMPT Creating Primary Key on 'GRUPO_HOJA_HC'
ALTER TABLE ANAMNESIS.GRUPO_HOJA_HC ADD (CONSTRAINT
 GHC_PK PRIMARY KEY
  (ID_GRUPO_HOJA_HC))
/



PROMPT Creating Check Constraint on 'GRUPO_HOJA_HC'
ALTER TABLE ANAMNESIS.GRUPO_HOJA_HC
 ADD (CONSTRAINT CK_GRUPO_HOJA CHECK (GRUPO IN ('MEDICO', 'ENFERMERIA')))
/



CREATE PUBLIC SYNONYM GRUPO_HOJA_HC FOR anamnesis.GRUPO_HOJA_HC;