SELECT p.nombres||' '||p.apellidos, P.CI,  calcular_edad(P.FECHA_NACIMIENTO),
       CASE WHEN V."DENTRO_RANGO_ESPAÑOL" IS NOT NULL THEN
            'DESCARTADA'
       ELSE
          CASE WHEN "FUERA_RANGO_ESPAÑOL" IS NULL THEN
              'DESCARTADA'
          ELSE
              'CONFIRMADA'
          END
       END RESULTADO,
       V.ID_PEDIDO
FROM   INTERNADO I,
       PAC P,
       V_RESULTADOS_LABORATORIO_HUSL v
WHERE  I.PAC_ID_PACIENTE = P.ID_PACIENTE
AND    P.ID_PACIENTE = V.ID_PACIENTE
AND    I.FECHA_DECESO IS NOT NULL
AND    I.SUCURSAL_ID_SUCURSAL = 5
AND    Trunc(I.FECHA_INICIO, 'DD') >= To_Date('01-01-20','dd-mm-rr')
AND    V.CODIGO_SERVICIO = 662443
AND    V."DENTRO_RANGO_ESPAÑOL" IS NULL
AND    "FUERA_RANGO_ESPAÑOL" IS NOT NULL
ORDER BY 1