SELECT *
FROM persona
WHERE ci= '5034124';


SELECT*
FROM persona
WHERE Upper(APELLIDOS) LIKE  '%CHIUZANO%';

SELECT DISTINCT grantee
FROM DBA_ROLE_PRIVS
WHERE granted_role IN ('R_TESORERIA','R_CONTABLE','R_CONSULTA_GERENTE','R_AUDITOR','R_GERENTE','R_GIRADURIA','R_GERENTE_ADM','R_GERENTE_ADM');

DROP USER pruebam;

SELECT *
FROM PERSONA
WHERE Upper(APELLIDOS) LIKE '%CHIUZANO%'





CREATE USER pruebam IDENTIFIED BY 12345;


DROP USER pruebam;

SELECT 'GRANT '||GRANTED_ROLE|| ' TO PRUEBAM;'
FROM DBA_ROLE_PRIVS
WHERE GRANTEE  = 'CANETEG';
ORDER BY 2;

GRANT R_RECURSO_HUMANO TO PRUEBAM;
GRANT R_MEDICO TO PRUEBAM;
GRANT R_INTERNADOS TO PRUEBAM;
GRANT R_GERENTE_ADM TO PRUEBAM;
GRANT R_EVALUACION_DESEMPENO TO PRUEBAM;
GRANT R_JEFE_AREA TO PRUEBAM;
GRANT R_TESORERIA TO PRUEBAM;
GRANT R_FACTURACION TO PRUEBAM;
GRANT R_COMUN TO PRUEBAM;
GRANT R_CENTRO_DIAGNOSTICO TO PRUEBAM;
GRANT R_ARTICULO TO PRUEBAM;
GRANT R_PROVEEDOR TO PRUEBAM;
GRANT R_CONTABILIDAD TO PRUEBAM;
GRANT R_CONTABLE TO PRUEBAM;
GRANT R_ENFERMERIA TO PRUEBAM;
GRANT R_FARMACIA TO PRUEBAM;
GRANT R_VER_HONORARIOS TO PRUEBAM;

GRANT EXECUTE ON ANAMNESIS.GENERA_OCIOSIDAD_CONSULTORIO TO R_GERENTE;

SELECT *
FROM persona
WHERE usuario = 'PRUEBAM';

UPDATE persona SET  sucursal_id_sucursal = 5 WHERE  id_persona = 3090;

COMMIT;

SELECT *
FROM LAVADO
WHERE USUARIO = 'PRUEBAM';

UPDATE PERSONA SET sucursal_id_sucursal = 4 WHERE  id_persona = 3090;



CREATE USER PRUEBAM IDENTIFIED BY 12345;



SELECT *
FROM dba_users
where username = 'MENDOZAC'

SELECT *
FROM frm_producto;
WHERE grantee = 'CHIUZANOE';

REVOKE R_RESULTADOS_LAB FROM pruebam;
REVOKE R_COORD_LAB FROM pruebam;

SELECT *
DELETE FROM pre_ord_comp
WHERE id_pre_orden = 9399;


REVOKE R_COBERTURA_ASM FROM CESTER;
DROP USER PRUEBAM;

EXEC ANAMNESIS.CREAR_VARIOS_USUARIOS('MENDOZAC');

   SELECT *
   FROM det_pre_ord_comp
   WHERE pop_id_pre_orden = 9401;

DELETE FROM pre_ord_comp
WHERE id_pre_orden = '9401'


UPDATE PERSONA SET IP_PC = '172.19.17.121', SUCURSAL_ID_SUCURSAL = 5 WHERE USUARIO IN('ECOGRAFIAHUSL');
COMMIT;


ALTER USER ENDOSCOPIAHUSL ACCOUNT UNLOCK;


ALTER USER ENDOSCOPIAHUSL IDENTIFIED BY sanlorenzo2017;

                   TIPO_UM ,
                   PROV ,
                   ARTICULO ,
                   PRECIO_PROVEEDOR ,
                   PRE_ORD_COMP ,
                   DET_PRE_ORD_COMP

SELECT *
FROM DBA_TAB_PRIVS
WHERE Upper(table_name) LIKE '%NOMEN_EMP%'
AND grantee = 'R_USU_URGENGIA';
AND privilege = 'INSERT';

  ENVIA_MAIL_ORD_COMPRA


SELECT *
FROM ARTICULOS_LAB;

GRANT

GRANT SELECT ON ANAMNESIS.NOMEN_EMP TO R_USU_URGENCIA ;

SELECT BUSCAR_CODIGO_PRG('NOMEN_EMPRESA')
FROM DUAL;


GRANT INSERT ON ANAMNESIS.ARTICULO_NOMEN TO R_COORD_LAB ;



GRANT SELECT ON ANAMNESIS.ART_COD_BARRA TO R_COORD_LAB ;
GRANT UPDATE ON ANAMNESIS.ART_COD_BARRA TO R_COORD_LAB ;
GRANT INSERT ON ANAMNESIS.ART_COD_BARRA TO R_COORD_LAB ;

GRANT SELECT ON ANAMNESIS.PRE_ORD_COMP TO R_COORD_LAB ;
GRANT INSERT ON ANAMNESIS.PRE_ORD_COMP TO R_COORD_LAB ;

GRANT SELECT ON ANAMNESIS.PRE_ORD_COMP TO R_BIOQUIMICO_LAB ;
GRANT INSERT ON ANAMNESIS.PRE_ORD_COMP TO R_BIOQUIMICO_LAB ;

GRANT UPDATE(DESCRIPCION) ON ANAMNESIS.ARTICULO TO R_COORD_LAB;
GRANT UPDATE(CANT_DETERMIN_FRASCO) ON ANAMNESIS.ARTICULO TO R_COORD_LAB;
GRANT UPDATE(PORCENTAJE_MINIMO_RENDIMIENTO) ON ANAMNESIS.ARTICULO TO R_COORD_LAB;

GRANT SELECT ON ANAMNESIS.ARTICULO_NOMEN TO R_COORD_LAB ;
GRANT INSERT ON ANAMNESIS.ARTICULO_NOMEN TO R_COORD_LAB ;



SELECT *
FROM ART_COD_BARRA

REVOKE


SELECT *
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'MEZAVI';

MAIDANAA
AREVALOSAL


SELECT *
FROM persona
WHERE UPPER(NOMBRES) LIKE '%VIVIANA%'
AND UPPER (APELLIDOS) LIKE '%MEZA%';



