CREATE USER BENITEZS IDENTIFIED BY BENITEZS2018 PROFILE SANATORIO;
--ALTER USER SOSAR PROFILE SANATORIO;


GRANT R_COMUN TO BENITEZS;
GRANT R_COMUNES TO BENITEZS;
GRANT R_CONTABLE,R_PROVEEDOR,R_TESORERIA,R_CONTABILIDAD TO BENITEZS;


SELECT 'GRANT '||GRANTED_ROLE|| ' TO SOSAR;'
FROM DBA_ROLE_PRIVS
WHERE GRANTEE  = 'FMYRTA';
ORDER BY 2;

SELECT *
FROM PERSONA_RRHH
WHERE Upper(NOMBRES) LIKE '%%'
AND Upper(APELLIDOS) LIKE '%FARIAS%';


SELECT *
FROM  DEPARTAMENTO_JN
WHERE id_departamento = 156;


SELECT *
FROM dba_users
WHERE username = 'OVELARJ';

INSERT INTO PERFIL VALUES('BENITEZS',SYSDATE,'LEGAL','MOTOR',SYSDATE,SYSDATE,'WIN-XP');
COMMIT;



SELECT *
FROM dba_ROLE_privs
WHERE GRANTEE = 'RAMIREZC';




SELECT *
FROM persona
WHERE USUARIO = 'PORTILLOL';


SELECT *
FROM persona_rrhh
WHERE Upper(nombres) LIKE  '%JAMIN%'
AND Upper(APELLIDOS) LIKE '%FERREIRA%';


SELECT *
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'FERREIRAJ'
ORDER BY 2;



SELECT *
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'MERELESJ'
ORDER BY 2 ;


REVOKE R_COMEDOR, R_LIBRO_COMPRA FROM FERREIRAJ;



SELECT *
FROM DBA_USERS
WHERE USERNAME = 'FERREIRAJ'

ALTER USER FERREIRAJ ACCOUNT UNLOCK;
ALTER USER FERREIRAJ IDENTIFIED BY lacosta2018;