PROMPT CREATE OR REPLACE VIEW anamnesis.v_int_prepaga_suc
CREATE OR REPLACE VIEW anamnesis.v_int_prepaga_suc (
  empresa_prepaga,
  habitacion_id_habitacion,
  id_paciente,
  id_internado,
  fecha_inicio,
  fecha_fin,
  obs,
  nombres,
  firma_cp,
  emp_plan_emp_id_empresa,
  emp_plan_plan_id_plan,
  id_sucursal
) AS
SELECT E.RAZ_SOC EMPRESA_PREPAGA,
       INTE.HABITACION_ID_HABITACION,
       PA.ID_PACIENTE,
       INTE.ID_INTERNADO,
       INTE.FECHA_INICIO,
       INTE.FECHA_FIN,
       INTE.OBS,
       PA.APELLIDOS||', '||PA.NOMBRES NOMBRES,
       INTE.FIRMA_CP,
       PA.EMP_PLAN_EMP_ID_EMPRESA,
       PA.EMP_PLAN_PLAN_ID_PLAN,
       H.PISO_SUCURSAL_ID_SUCURSAL
FROM HABITACION@ssr H,
     EMP@ssr E,
     PAC@ssr PA,
     TIPO_HABITACION@ssr TH,
(SELECT I.HABITACION_ID_HABITACION,
        P.ID_PACIENTE,
        I.ID_INTERNADO,
        I.FECHA_INICIO,
        I.FECHA_FIN,
        I.OBS,
        P.APELLIDOS||', '||P.NOMBRES NOMBRES,
        NVL(I.FIRMA_CP, 'NO') FIRMA_CP
FROM    PAC@ssr P ,INTERNADO@ssr I
WHERE   P.ID_PACIENTE = I.PAC_ID_PACIENTE
AND     I.FECHA_FIN IS NULL) INTE
WHERE   INTE.HABITACION_ID_HABITACION = H.ID_HABITACION
AND     TH.AFECTA_OCUPACION = 'SI'
AND     H.ESTADO_HAB = 'ACTIVO'
AND     H.TIP_HABIT_ID_TIPO_HABITACION = TH.ID_TIPO_HABITACION
AND     PA.ID_PACIENTE(+) = INTE.ID_PACIENTE
AND     PA.EMP_PLAN_EMP_ID_EMPRESA  = E.ID_EMPRESA(+)
UNION ALL
SELECT E.RAZ_SOC EMPRESA_PREPAGA,
       INTE.HABITACION_ID_HABITACION,
       PA.ID_PACIENTE,
       INTE.ID_INTERNADO,
       INTE.FECHA_INICIO,
       INTE.FECHA_FIN,
       INTE.OBS,
       PA.APELLIDOS||', '||PA.NOMBRES NOMBRES,
       INTE.FIRMA_CP,
       PA.EMP_PLAN_EMP_ID_EMPRESA,
       PA.EMP_PLAN_PLAN_ID_PLAN,
       H.PISO_SUCURSAL_ID_SUCURSAL
FROM HABITACION H,
     EMP E,
     PAC PA,
     TIPO_HABITACION TH,
(SELECT I.HABITACION_ID_HABITACION,
        P.ID_PACIENTE,
        I.ID_INTERNADO,
        I.FECHA_INICIO,
        I.FECHA_FIN,
        I.OBS,
        P.APELLIDOS||', '||P.NOMBRES NOMBRES,
        NVL(I.FIRMA_CP, 'NO') FIRMA_CP
FROM    PAC P ,INTERNADO I
WHERE   P.ID_PACIENTE = I.PAC_ID_PACIENTE
AND     I.FECHA_FIN IS NULL) INTE
WHERE   INTE.HABITACION_ID_HABITACION = H.ID_HABITACION
AND     TH.AFECTA_OCUPACION = 'SI'
AND     H.ESTADO_HAB = 'ACTIVO'
AND     H.TIP_HABIT_ID_TIPO_HABITACION = TH.ID_TIPO_HABITACION
AND     PA.ID_PACIENTE(+) = INTE.ID_PACIENTE
AND     PA.EMP_PLAN_EMP_ID_EMPRESA  = E.ID_EMPRESA(+)
/

GRANT SELECT ON anamnesis.v_int_prepaga_suc TO r_dpto_admision;
GRANT SELECT ON anamnesis.v_int_prepaga_suc TO r_gerente;
GRANT SELECT ON anamnesis.v_int_prepaga_suc TO r_gerente_adm;
GRANT SELECT ON anamnesis.v_int_prepaga_suc TO r_jefe_cdx;
